### ISSUE TITLE
cannot browse folder shared from CERNBox to OC-10

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#215]
<img width="707" alt="Screenshot 2023-06-13 at 14 49 12" src="https://github.com/pondersource/sciencemesh-php/assets/408412/d8e24420-9b7d-44a8-a032-9155fa256052">

owncloud log:
```
{"reqId":"VnDIZbGbsVdijwdyC59s","level":3,"time":"2023-06-13T12:45:00+00:00","remoteAddr":"192.87.118.119","user":"einstein","app":"no app in context","method":"GET","url":"\/remote.php\/webdav\/shared-sciencemesh","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"remote root vanished\",\"Code\":1,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(194): OC\\\\Files\\\\Storage\\\\DAV->hasUpdated()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(384): OCA\\\\Files_Sharing\\\\External\\\\Storage->hasUpdated()\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(394): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(384): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->hasUpdated()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(384): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Watcher.php(130): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated()\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Watcher.php(38): OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1412): OCA\\\\Files_Sharing\\\\External\\\\Watcher->needsUpdate()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1452): OC\\\\Files\\\\View->getCacheEntry()\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(178): OC\\\\Files\\\\View->getFileInfo()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/DAV\\\/ViewOnlyPlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath()\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\DAV\\\\ViewOnlyPlugin->checkViewOnly()\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#15 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":802}"}
{"reqId":"VnDIZbGbsVdijwdyC59s","level":3,"time":"2023-06-13T12:45:00+00:00","remoteAddr":"192.87.118.119","user":"einstein","app":"files_external","method":"GET","url":"\/remote.php\/webdav\/shared-sciencemesh","message":"remote root vanished"}
{"reqId":"VnDIZbGbsVdijwdyC59s","level":3,"time":"2023-06-13T12:45:01+00:00","remoteAddr":"192.87.118.119","user":"einstein","app":"no app in context","method":"GET","url":"\/remote.php\/webdav\/shared-sciencemesh","message":"Storage for external share shared::d820dc57d820bc05e8c481f4b87562de returns not found error. Removing share as testing of remote succeeded."}
{"reqId":"VnDIZbGbsVdijwdyC59s","level":2,"time":"2023-06-13T12:45:01+00:00","remoteAddr":"192.87.118.119","user":"einstein","app":"no app in context","method":"GET","url":"\/remote.php\/webdav\/shared-sciencemesh","message":"Storage shared-sciencemesh is invalid"}

**Comment by michielbdejong** [comment]
logs on the CERNBox side:
```
138.68.152.182 - - [13/Jun/2023:14:45:00 +0200] "GET /ocm-provider/ HTTP/1.1" 200 429 "-" "ownCloud Server Crawler" "-"
138.68.152.182 - xZ4MhmUq1k94LtU25fOYm7QGbHOowWP8 [13/Jun/2023:14:45:00 +0200] "PROPFIND /remote.php/dav/ocm/ HTTP/2.0" 404 0 "-" "sabre-dav/4.4.0 (http://sabre.io/)" "-"
