### ISSUE TITLE
error enabling sciencemesh app

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#7]
```sh
An unhandled exception has been thrown:
Error: Undefined class constant 'BIGINT' in /var/www/html/apps/sciencemesh/lib/Migration/Version010000Date20210118175358.php:57
Stack trace:
#0 /var/www/html/lib/private/DB/MigrationService.php(455): OCA\ScienceMesh\Migration\Version010000Date20210118175358->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 /var/www/html/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly('latest')
#2 /var/www/html/lib/private/Installer.php(163): OC\DB\MigrationService->migrate('latest', true)
#3 /var/www/html/core/Command/App/Enable.php(123): OC\Installer->installApp('sciencemesh', false)
#4 /var/www/html/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('sciencemesh', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(100): OC\Console\Application->run()
#11 {main}configured
```

**Comment by michielbdejong** [comment]
I had a look at [this post](https://symfony.com/doc/current/doctrine/dbal.html) and hoped that [`php /install/composer.phar require symfony/orm-pack`](https://github.com/pondersource/sciencemesh-nextcloud/blob/main/docker/nc/Dockerfile#L19) would fix it, but I guess I'm out of my depth here. Looks like it's trying to use a BIGINT type that should [come from Doctrin/DBAL](https://github.com/pondersource/sciencemesh-nextcloud/blob/main/nc-sciencemesh/lib/Migration/Version010000Date20210118175358.php#L10) but maybe it needs something more somehow.

@ylebre can you have a look?

**Comment by ylebre** [comment]
Looks like it isn't running the autoloader.php from the vendor dir. Adding require_once(__DIR__ . "/../../vendor/autoload.php") just before the first 'use' statement fixes that part. It does give another error after that, but retrying the init after that gets it to 'sciencemesh 1.1.0 enabled'.
https://github.com/pondersource/sciencemesh-nextcloud/tree/bigint-fix

**Comment by michielbdejong** [comment]
New error:
```sh
$ ./nc-live.sh 
a245fe34ba4440cd63fa420bd247420fc0453aa55af645f03c2b8f3457ff7a5f
Waiting for Nextcloud to start on dockerbak, this can take up to a minute ...
CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS         PORTS     NAMES
a245fe34ba44   nc        "/entrypoint.sh apac…"   4 seconds ago   Up 2 seconds             nc_live
Initializing nextcloud 21.0.2.1 ...
Initializing finished
New nextcloud instance
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Jun 14 13:56:17.195068 2021] [ssl:warn] [pid 1] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jun 14 13:56:17.195149 2021] [ssl:warn] [pid 1] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Jun 14 13:56:17.238872 2021] [ssl:warn] [pid 1] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jun 14 13:56:17.238910 2021] [ssl:warn] [pid 1] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 14 13:56:17.242101 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.20 OpenSSL/1.1.1d configured -- resuming normal operations
[Mon Jun 14 13:56:17.242357 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
Nextcloud was successfully installed
  - installed: true
  - version: 21.0.2.1
  - versionstring: 21.0.2
  - edition: 
An unhandled exception has been thrown:
Error: Call to undefined method Doctrine\DBAL\Schema\Table::getUniqueConstraints() in /var/www/html/3rdparty/doctrine/dbal/src/Platforms/AbstractPlatform.php:1529
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/src/Platforms/SqlitePlatform.php(840): Doctrine\DBAL\Platforms\AbstractPlatform->getCreateTableSQL(Object(Doctrine\DBAL\Schema\Table), 1)
#1 /var/www/html/apps/sciencemesh/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php(144): Doctrine\DBAL\Platforms\SqlitePlatform->getCreateTableSQL(Object(Doctrine\DBAL\Schema\Table), 1)
#2 /var/www/html/apps/sciencemesh/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php(100): Doctrine\DBAL\Schema\SchemaDiff->_toSql(Object(OC\DB\OCSqlitePlatform), false)
#3 /var/www/html/lib/private/DB/Migrator.php(252): Doctrine\DBAL\Schema\SchemaDiff->toSql(Object(OC\DB\OCSqlitePlatform))
#4 /var/www/html/lib/private/DB/Migrator.php(90): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))
#5 /var/www/html/lib/private/DB/Connection.php(524): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))
#6 /var/www/html/lib/private/DB/MigrationService.php(464): OC\DB\Connection->migrateToSchema(Object(Doctrine\DBAL\Schema\Schema))
#7 /var/www/html/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly('latest')
#8 /var/www/html/lib/private/Installer.php(163): OC\DB\MigrationService->migrate('latest', true)
#9 /var/www/html/core/Command/App/Enable.php(123): OC\Installer->installApp('sciencemesh', false)
#10 /var/www/html/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('sciencemesh', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(100): OC\Console\Application->run()
#17 {main}configured
[ ok ] Reloading Apache httpd web server: apache2.
```

**Comment by michielbdejong** [comment]
This works though:
```sh
rm nc-sciencemesh/lib/Migration/Version010000Date20210118175358.php
./build.sh
./nc-live.sh
[...]
Nextcloud was successfully installed
  - installed: true
  - version: 21.0.2.1
  - versionstring: 21.0.2
  - edition: 
sciencemesh 1.1.0 enabled
configured
[ ok ] Reloading Apache httpd web server: apache2.
```

**Comment by ylebre** [comment]
Ok - lets use this as a starting point. Removing the migration means we won't have the database to write in, but I don't think we need it at this point. The calls that make use of it are of course broken now :)

**Comment by michielbdejong** [comment]
ok! i'll merge that workaround then.
